[project]
name = "youtube-download-helper"
version = "0.1.0"
description = "Add your description here"
authors = [
  { name="JÃ¼rgen Schoenemeyer", email="js007@web.de" },
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "yt-dlp==2024.12.23",
]
